import { mkdir, readFile, writeFile as writeRaw } from "node:fs/promises";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { root, outputRoot, uiOutput, type BrandBuild } from "./resolve.mjs";

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll('"', "&quot;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll("'", "&#39;");
}
export async function generateConfig(build: BrandBuild): Promise<void> {
  const { brand, version, fingerprint } = build;
  const json = (value: unknown) => JSON.stringify(value, null, 2) + "\n";
  const generated = path.join(root, "packages/branding/src/generated");
  await mkdir(generated, { recursive: true });
  await writeFile(
    path.join(generated, "brand.ts"),
    `// Generated by brand:prepare.\nimport type { Brand } from "../schema.js";\nexport const resolvedBrand: Brand = ${json(brand).trim()};\n`,
  );
  await writeFile(path.join(outputRoot, "brand.json"), json(brand));
  const iconPath = (name: string) => path.join(outputRoot, "icons", name);
  const overlay = {
    productName: brand.name,
    identifier: brand.applicationId,
    version,
    mainBinaryName: brand.desktopBinaryName,
    bundle: {
      publisher: brand.publisher,
      shortDescription: brand.name,
      longDescription: brand.description,
      icon: ["32x32.png", "128x128.png", "128x128@2x.png", "icon.icns", "icon.ico"].map(iconPath),
      windows: {
        nsis: { installerIcon: iconPath("icon.ico"), uninstallerIcon: iconPath("icon.ico") },
      },
      createUpdaterArtifacts: brand.distribution.updateMode === "tauri-signed",
    },
    plugins: {
      "deep-link": { desktop: { schemes: [brand.scheme] } },
      updater: {
        pubkey: brand.distribution.updaterPublicKey ?? "REPLACE_WITH_MINISIGN_PUBLIC_KEY",
        endpoints: brand.distribution.releaseBase
          ? [`${brand.distribution.releaseBase}/latest/download/latest.json`]
          : [],
      },
    },
  };
  await writeFile(path.join(outputRoot, "tauri.conf.json"), json(overlay));
  const manifest = JSON.parse(
    await readFile(path.join(root, "apps/ui/public/manifest.json"), "utf8"),
  );
  Object.assign(manifest, {
    id: brand.legacyFde ? "/" : `/${brand.id}`,
    name: brand.name,
    short_name: brand.name,
    description: brand.description,
    theme_color: brand.colors.dark.accent,
    background_color: brand.colors.dark.background,
  });
  await writeFile(path.join(uiOutput, "public/manifest.json"), json(manifest));
  let html = await readFile(path.join(root, "apps/ui/public/index.html"), "utf8");
  html = html
    .replace('content="FDE"', `content="${escapeHtml(brand.name)}"`)
    .replaceAll("#25B5C8", brand.colors.dark.accent)
    .replaceAll("#25b5c8", brand.colors.dark.accent)
    .replaceAll("#181b1a", brand.colors.dark.background);
  await writeFile(path.join(uiOutput, "public/index.html"), html);
  const eas = JSON.parse(await readFile(path.join(root, "apps/ui/eas.json"), "utf8"));
  if (brand.distribution.iosStoreId)
    eas.submit.production.ios = { ascAppId: brand.distribution.iosStoreId };
  else delete eas.submit.production.ios;
  await writeFile(path.join(outputRoot, "eas.json"), json(eas));
  const revision = execFileSync("git", ["rev-parse", "HEAD"], {
    cwd: root,
    encoding: "utf8",
  }).trim();
  await writeFile(
    path.join(outputRoot, "provenance.json"),
    json({
      schemaVersion: 1,
      brand: { id: brand.id, applicationId: brand.applicationId },
      version,
      sourceRevision: revision,
      configFingerprint: fingerprint,
    }),
  );
  const constants: Record<string, string | number | boolean> = {
    ID: brand.id,
    VERSION: version,
    CONFIG_FINGERPRINT: fingerprint,
    SOURCE_REVISION: revision,
    NAME: brand.name,
    FULL_NAME: brand.fullName,
    APPLICATION_ID: brand.applicationId,
    CLI_NAME: brand.cliName,
    DESKTOP_BINARY: brand.desktopBinaryName,
    HOME_DIR: brand.homeDir,
    ENV_PREFIX: brand.envPrefix,
    SCHEME: brand.scheme,
    SERVICE_NAME: brand.serviceName,
    LAUNCHD_LABEL: brand.launchdLabel,
    ARTIFACT_PREFIX: brand.artifactPrefix,
    DAEMON_ARTIFACT_PREFIX: brand.daemonArtifactPrefix,
    DEFAULT_PORT: brand.daemonPort,
    LEGACY_FDE: brand.legacyFde,
    RELEASES_API: brand.distribution.releasesApi ?? "",
    RELEASE_BASE: brand.distribution.releaseBase ?? "",
    UPDATE_MODE: brand.distribution.updateMode,
  };
  const rust = Object.entries(constants)
    .map(([name, value]) => `pub const ${name}: ${rustType(value)} = ${JSON.stringify(value)};`)
    .join("\n");
  await writeFile(path.join(outputRoot, "brand.rs"), `// Generated by brand:prepare.\n${rust}\n`);
}

function rustType(value: string | number | boolean): string {
  if (typeof value === "number") return "u16";
  if (typeof value === "boolean") return "bool";
  return "&str";
}

async function writeFile(file: string, contents: string): Promise<void> {
  try {
    if ((await readFile(file, "utf8")) === contents) return;
  } catch {
    /* New output. */
  }
  await writeRaw(file, contents);
}
