import { mkdir, readFile, writeFile as writeBytes } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";
import type { Brand } from "../../../packages/branding/src/schema.js";
import { writeFile } from "./config.mjs";
import { outputRoot, root, type BrandBuild } from "./resolve.mjs";

/** Logical window size; every coordinate in the NSIS template is in these units. */
export const installerWindow = {
  width: 440,
  height: 300,
  hero: 136,
  logo: 72,
  logoTop: 40,
} as const;
/** Bitmap sets for the DPI buckets the installer picks between at runtime. */
export const installerScales = [100, 125, 150, 200] as const;

const templateFile = path.join(root, "packages/branding/templates/windows-installer.nsh");

/** NSIS string literal escaping; brand text is already free of control characters. */
export function nsisString(value: string): string {
  return value.replaceAll("$", "$$$$").replaceAll('"', '$\\"').replaceAll("`", "$\\`");
}
/** NSIS SetCtlColors takes RRGGBB; Win32 COLORREF is 0x00BBGGRR. */
const rgb = (hex: string) => hex.slice(1).toUpperCase();
const colorref = (hex: string) =>
  `0x00${hex.slice(5, 7)}${hex.slice(3, 5)}${hex.slice(1, 3)}`.toUpperCase().replace("0X", "0x");

/** Windows folder names cannot carry every brand character; fall back to the slug id. */
export function installDirectoryName(brand: Pick<Brand, "name" | "id">): string {
  return /^[-_+0-9a-zA-Z .]+$/.test(brand.name) && !brand.name.endsWith(".")
    ? brand.name
    : brand.id;
}

export function renderInstallerDefines(brand: Brand): string {
  const { installer } = brand;
  const defines: Record<string, string> = {
    NAME: brand.name,
    PUBLISHER: brand.publisher,
    TAGLINE: installer.tagline,
    INSTALL_DIR_NAME: installDirectoryName(brand),
    COPY_INSTALLING: installer.copy.installing,
    COPY_MIGRATING: installer.copy.migrating,
    COPY_READY: installer.copy.ready,
    COPY_LAUNCHING: installer.copy.launching,
    COPY_ELEVATION_REQUIRED: installer.copy.elevationRequired,
    WIDTH: String(installerWindow.width),
    HEIGHT: String(installerWindow.height),
  };
  for (const [key, value] of Object.entries(installer.colors)) {
    const name = key.replace(/[A-Z]/g, (letter) => `_${letter}`).toUpperCase();
    defines[`COLOR_${name}`] = rgb(value);
    defines[`COLORREF_${name}`] = colorref(value);
  }
  return (
    `; Generated by brand:prepare from brand.json. Do not edit.\n` +
    Object.entries(defines)
      .map(([key, value]) => `!define BRAND_INSTALLER_${key} "${nsisString(value)}"`)
      .join("\n") +
    "\n"
  );
}

function backgroundSvg(brand: Brand, scale: number): string {
  const { width, hero: height } = installerWindow;
  const { colors } = brand.installer;
  const w = Math.round((width * scale) / 100);
  const h = Math.round((height * scale) / 100);
  const s = scale / 100;
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">
  <defs>
    <radialGradient id="glow" cx="50%" cy="0%" r="100%">
      <stop offset="0%" stop-color="${colors.accent}" stop-opacity="0.30"/>
      <stop offset="55%" stop-color="${colors.accent}" stop-opacity="0.06"/>
      <stop offset="100%" stop-color="${colors.accent}" stop-opacity="0"/>
    </radialGradient>
  </defs>
  <rect width="${w}" height="${h}" fill="${colors.background}"/>
  <rect width="${w}" height="${h}" fill="url(#glow)"/>
  <circle cx="${w / 2}" cy="${
    (installerWindow.logoTop + installerWindow.logo / 2) * s
  }" r="${52 * s}" fill="${colors.surface}" fill-opacity="0.9" stroke="${
    colors.accent
  }" stroke-opacity="0.28" stroke-width="${Math.max(1, s)}"/>
</svg>`;
}

/** 24-bit bottom-up BMP: Win32 LoadImage reads it without GDI+ or extra plugins. */
export function encodeBmp(pixels: Buffer, width: number, height: number, channels: number): Buffer {
  const stride = Math.ceil((width * 3) / 4) * 4;
  const header = Buffer.alloc(54);
  const size = 54 + stride * height;
  header.write("BM", 0, "ascii");
  header.writeUInt32LE(size, 2);
  header.writeUInt32LE(54, 10);
  header.writeUInt32LE(40, 14);
  header.writeInt32LE(width, 18);
  header.writeInt32LE(height, 22);
  header.writeUInt16LE(1, 26);
  header.writeUInt16LE(24, 28);
  header.writeUInt32LE(stride * height, 34);
  const body = Buffer.alloc(stride * height);
  for (let y = 0; y < height; y++) {
    const row = (height - 1 - y) * stride;
    for (let x = 0; x < width; x++) {
      const source = (y * width + x) * channels;
      body[row + x * 3] = pixels[source + 2];
      body[row + x * 3 + 1] = pixels[source + 1];
      body[row + x * 3 + 2] = pixels[source];
    }
  }
  return Buffer.concat([header, body]);
}

export async function renderInstallerBackground(
  brand: Brand,
  iconFile: string,
  scale: number,
): Promise<Buffer> {
  const s = scale / 100;
  const logo = Math.round(installerWindow.logo * s);
  const background = sharp(Buffer.from(backgroundSvg(brand, scale)));
  const { width } = await background.metadata();
  const mark = await sharp(iconFile).resize(logo, logo, { fit: "contain" }).png().toBuffer();
  const { data, info } = await background
    .composite([
      {
        input: mark,
        left: Math.round((width! - logo) / 2),
        top: Math.round(installerWindow.logoTop * s),
      },
    ])
    .removeAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });
  return encodeBmp(data, info.width, info.height, info.channels);
}

/** Writes the brand defines, the template and per-DPI artwork into one include directory. */
export async function renderWindowsInstaller(
  brand: Brand,
  iconFile: string,
  directory: string,
): Promise<string[]> {
  await mkdir(directory, { recursive: true });
  const written: string[] = [];
  const emit = async (name: string, contents: string | Buffer) => {
    const file = path.join(directory, name);
    if (typeof contents === "string") await writeFile(file, contents);
    else await writeBytes(file, contents);
    written.push(file);
  };
  await emit("brand.nsh", renderInstallerDefines(brand));
  await emit("installer.nsh", (await readFile(templateFile, "utf8")).replaceAll("\r\n", "\n"));
  for (const scale of installerScales)
    await emit(`background-${scale}.bmp`, await renderInstallerBackground(brand, iconFile, scale));
  return written;
}

export async function generateWindowsInstaller(build: BrandBuild): Promise<void> {
  await renderWindowsInstaller(
    build.brand,
    build.assetFiles.icon,
    path.join(outputRoot, "windows-installer"),
  );
}
